Vagrant.configure(2) do |config|

  config.vm.define "nagiosserver" do |nagiosserver|

    nagiosserver.vm.box = "ubuntu/trusty64"
    nagiosserver.vm.hostname = "nagiosserver"
    nagiosserver.vm.network "private_network", ip: "192.168.33.10"

    nagiosserver.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end

    nagiosserver.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.provision.yml"
      ansible.inventory_path = "local_inventory.ini"
      ansible.sudo = true
      ansible.verbose = "v"
    end

  end

  config.vm.define "nagioshost" do |nagioshost|

    nagioshost.vm.box = "ubuntu/trusty64"
    nagioshost.vm.hostname = "nagioshost"
    nagioshost.vm.network "private_network", ip: "192.168.33.11"

    nagioshost.vm.provider "virtualbox" do |vb|
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end

    nagioshost.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.provision.yml"
      ansible.inventory_path = "local_inventory.ini"
      ansible.sudo = true
      ansible.verbose = "v"
    end

  end

end
